//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GuessWhoContainer : DbContext
    {
        public GuessWhoContainer()
            : base("name=GuessWhoContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Player> Player { get; set; }
        public DbSet<Country> Country { get; set; }
        public DbSet<Level> Level { get; set; }
        public DbSet<Decade> Decade { get; set; }
    }
}
