//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Picture { get; set; }
        public bool IsPublished { get; set; }
        public int CountryId { get; set; }
        public int DecadeId { get; set; }
        public int LevelId { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Decade Decade { get; set; }
        public virtual Level Level { get; set; }
    }
}
